excerpt_separator: ""
pygments: true
markdown: kramdown
title: web.ROAD
tagline: Desenvolvimento Web
description: Tudo sobre desenvolvimento web ;)
paginate: 5
author:
  reidark:
    name: reidark
    url: http://reidark.github.io
    description: Estudando desenvolvimento web desde sempre
