excerpt_separator: ""
pygments: true
markdown: kramdown
title: reidark
tagline: code to back home
description: code with melancholic track
paginate: 5
author:
  reidark:
    name: reidark
    url: http://reidark.github.io
    description: Estudando desenvolvimento web desde sempre
